version: 0.0
os: linux

files:
  # Deploy Node/Express server
  - source: server
    destination: /var/www/React-Crud_nodewithSql_App/server

  # Deploy built React client (from CodeBuild artifact)
  - source: client/build
    destination: /var/www/React-Crud_nodewithSql_App/client

permissions:
  - object: /var/www/React-Crud_nodewithSql_App
    pattern: "**"
    owner: ec2-user
    group: ec2-user
    mode: 755
    type:
      - file
      - directory

hooks:
  ApplicationStop:
    - location: scripts/stop_server.sh
      timeout: 60
      runas: ubuntu

  BeforeInstall:
    - location: scripts/clean_old.sh
      timeout: 180
      runas: ubuntu

  AfterInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu 

  ApplicationStart:
    - location: scripts/start_server.sh
      timeout: 300
      runas: ubuntu 

  ValidateService:
    - location: scripts/validate_service.sh
      timeout: 60
      runas: ubuntu
