version: 0.2

phases:
  install:
    commands:
      - echo "Installing server dependencies..."
      - cd server
      - npm ci || npm install
      - cd ..
      - echo "Installing client dependencies..."
      - cd client
      - npm ci || npm install
      - cd ..

  pre_build:
    commands:
      - echo "Running pre-build lint on SERVER..."
      - pwd
      - ls
      - cd server
      - pwd          # should end with /server
      - ls           # should show server/package.json
      - npm audit || echo "npm audit failed (non-fatal), continuing..."
      - cd ..

  build:
    commands:
      - echo "Building CLIENT..."
      - cd client
      - npm run build
      - cd ..
      - echo "Building SERVER (if build script exists)..."
      - cd server
      - npm run build || echo "No server build step, skipping"
      - cd ..

  post_build:
    commands:
      - echo "Post-build stage (no npm test to avoid failing build)..."
      # If you later have real tests, uncomment:
      # - cd server
      # - npm test
      # - cd ..
      - echo "Build completed successfully!"

artifacts:
  files:
    - client/build/**/*
    - server/**/*
