version: 0.2

phases:
  pre_build:
    commands:
      - echo "Running pre-build checks..."
      - npm run lint # Or your preferred linter command
      - npm audit # Optional: Checks for security vulnerabilities in your dependencies

  install:
    commands:
      - echo "Installing server dependencies..."
      - cd server
      - npm ci
      - cd ..
      - echo "Installing client dependencies..."
      - cd client
      - npm ci
      - cd ..

  build:
    commands:
      - echo "Building client..."
      - cd client
      - npm run build
      - cd ..
      # If server has a build step:
      - echo "Building server..."
      - cd server
      - npm run build || echo "No server build step, skipping"
      - cd ..

  post_build:
    commands:
      - echo "Running post-build tasks..."
      - npm test # Runs your unit and integration tests
      - echo "Build completed successfully!"

artifacts:
  files:
    - client/build/**/*   # client build
    - server/**/*         # server app, if you want to package it too
